name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [8.*, 9.*, 10.*, 11.*, 12.*]
        dependency-version: [prefer-stable]
        include:
          - laravel: 8.*
            testbench: ^6.0
            phpunit: ^9.0
          - laravel: 9.*
            testbench: ^7.0
            phpunit: ^9.0
          - laravel: 10.*
            testbench: ^8.0
            phpunit: ^10.0
          - laravel: 11.*
            testbench: ^9.0
            phpunit: ^10.0
          - laravel: 12.*
            testbench: ^10.0
            phpunit: ^11.0
        exclude:
          # Laravel 8 requires PHP 8.0-8.1 (we'll allow 8.1 only)
          - laravel: 8.*
            php: 8.2
          - laravel: 8.*
            php: 8.3
          # Laravel 9 requires PHP 8.0-8.2 (we'll allow 8.1-8.2)
          - laravel: 9.*
            php: 8.3
          # Laravel 11 requires PHP 8.2+
          - laravel: 11.*
            php: 8.1
          # Laravel 12 requires PHP 8.2+
          - laravel: 12.*
            php: 8.1

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl
        coverage: xdebug

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress

    - name: List Installed Dependencies
      run: composer show laravel/framework orchestra/testbench phpunit/phpunit

    - name: Execute tests
      run: vendor/bin/phpunit --testdox --coverage-text

    - name: Generate coverage report
      if: matrix.php == '8.2' && matrix.laravel == '12.*'
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      if: matrix.php == '8.2' && matrix.laravel == '12.*'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
